# Generated by Django 6.0.7 on 2026-07-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_alter_donor_address_alter_donor_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
