# Generated by Django 6.0.7 on 2026-08-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_bloodrequest_required_date_bloodrequest_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='request_for',
            field=models.CharField(choices=[('self', 'Myself'), ('other', 'Someone Else')], default='self', max_length=10),
        ),
    ]
